const placeholder = '/placeholder.svg'
const avatarPlaceholder = '/placeholder-avatar.svg'

export const deck = {
  title: '你的主题标题',
  subtitle: '一句话说明这场分享为什么值得听',
  speaker: {
    name: '你的姓名',
    role: '你的职位 · 你的组织',
    account: '@your-account',
  },
  slides: [
    {
      id: 'cover',
      type: 'cover',
      theme: 'dark',
      eyebrow: 'YOUR TOPIC',
      titleLines: ['向前走', '一步'],
      subtitle: 'Vibe Coding，没你想的那么难',
    },
    {
      id: 'background',
      type: 'profile',
      theme: 'dark',
      eyebrow: '01 / 背景',
      title: '你正在做什么？',
      lead: '用两三句话交代你的背景、问题和正在推进的事情。',
      facts: [
        { label: '领域', value: '你的行业 / 方向' },
        { label: '阶段', value: '探索 / 验证 / 发布' },
        { label: '目标', value: '你希望听众记住什么' },
      ],
      image: placeholder,
    },
    {
      id: 'projects',
      type: 'gallery',
      theme: 'paper',
      eyebrow: '02 / 作品',
      title: '你的项目与尝试',
      lead: '把项目、实验或案例放在同一个视觉轨道里。',
      items: [
        { title: '项目 A', description: '一句话描述项目 A', image: placeholder },
        { title: '项目 B', description: '一句话描述项目 B', image: placeholder },
        { title: '项目 C', description: '一句话描述项目 C', image: placeholder },
      ],
    },
    {
      id: 'chapter-one',
      type: 'chapter',
      theme: 'dark',
      index: '01',
      overline: 'ACT 01',
      title: '为什么这件事没那么难',
      subtitle: '用一个明确判断，把听众带进你的第一个章节。',
    },
    {
      id: 'method',
      type: 'pipeline',
      theme: 'paper',
      eyebrow: '03 / 方法',
      title: '把复杂工作拆成可见的步骤。',
      lead: '每一块只承担一个职责，读者就能快速理解你的方法。',
      steps: [
        { label: '输入', title: '需求与判断', description: '说清楚要解决什么' },
        { label: '过程', title: '你的方法', description: '看得见，改得动' },
        { label: '承接', title: '工具与协作', description: '数据 · 权限 · 交付' },
        { label: '输出', title: '能用的结果', description: '让下一步自然发生' },
      ],
      note: '一条结论，解释为什么这套方法对听众有用。',
    },
    {
      id: 'stat',
      type: 'stat',
      theme: 'dark',
      eyebrow: '04 / 证据',
      title: '用一个可信数字制造停顿。',
      value: '99',
      suffix: '%',
      caption: '你的核心证据 / 覆盖率 / 增长结果',
    },
    {
      id: 'loop',
      type: 'flow',
      theme: 'paper',
      eyebrow: '05 / 例子',
      title: '从想法到结果的反馈回路',
      pain: '先做一个最小闭环，再用真实反馈修正它。',
      loop: ['问问题', '动手试', '看到结果', '带着错误再问'],
      punch: '试错成本低，反馈速度快。',
    },
    {
      id: 'chapter-two',
      type: 'chapter',
      theme: 'dark',
      index: '02',
      overline: 'ACT 02',
      title: '先想清楚，再动手',
      subtitle: '第二章可以切换到策略、判断或方法论。',
    },
    {
      id: 'roadmap',
      type: 'roadmap',
      theme: 'paper',
      eyebrow: '06 / 路线图',
      title: '把下一步变成三个动作。',
      steps: [
        { number: '01', title: '先记下来', description: '不要依赖三小时后的记忆。' },
        { number: '02', title: '问三个问题', description: '谁会用？为什么用？凭什么现在用？' },
        { number: '03', title: '砍到最小', description: '只保留一次完整、可验证的闭环。' },
      ],
      callout: '尽早发布',
    },
    {
      id: 'feedback',
      type: 'reviews',
      theme: 'split',
      eyebrow: '07 / 反馈',
      title: '把陌生人的评价放进画面。',
      description: '这块适合放用户反馈、调研摘录或真实对话。',
      stats: [
        { label: '反馈数', value: '42' },
        { label: '评分', value: '6.4' },
      ],
      reviews: [
        { name: '用户 A', text: '这里替换成一句真实反馈。', avatar: avatarPlaceholder },
        { name: '用户 B', text: '这里替换成一句不同角度的反馈。', avatar: avatarPlaceholder },
        { name: '用户 C', text: '这里替换成一句反对意见。', avatar: avatarPlaceholder },
        { name: '用户 D', text: '这里替换成一句可执行建议。', avatar: avatarPlaceholder },
      ],
      qr: '/placeholder-qr.svg',
    },
    {
      id: 'skills',
      type: 'skills',
      theme: 'paper',
      eyebrow: '08 / 能力',
      title: '把能力成长写成一条路。',
      items: [
        { level: '萌新', title: '先换皮', description: '先使用成熟组件和明确的视觉基线。' },
        { level: '入门', title: '无脑抄', description: '先复用可验证的提示词和案例。' },
        { level: '新手', title: '找现成库', description: '把时间花在问题，而不是重复造轮子。' },
        { level: '进阶', title: '别做缝合怪', description: '统一视觉语言，再让工具还原。' },
        { level: '开智', title: '看懂在说什么', description: '理解布局、动效、状态和密度。' },
        { level: '毕业', title: '先收藏，再复用', description: '建立自己的素材和组件资产库。' },
      ],
    },
    {
      id: 'closing',
      type: 'closing',
      theme: 'dark',
      eyebrow: '09 / 结论',
      statements: [
        { number: '01', title: '敢于承认自己还不会。', body: '把未知写下来，问题才会变得可解决。' },
        { number: '02', title: '敢于向前迈一步。', body: '想一下最坏的结果，发现也没那么坏。' },
      ],
    },
    {
      id: 'outro',
      type: 'outro',
      theme: 'dark',
      eyebrow: 'THANK YOU',
      title: '如果你还是不敢',
      body: '把这里替换成你的关注方式、联系方式或下一步邀请。',
      account: '@your-account',
      image: placeholder,
    },
  ],
}

